

#READ_DATA = 2  # TODO
#WRITE_DATA = 3  # TODO
#CW_ANGLE_LIMIT_L = 6  # TODO
#CCW_ANGLE_LIMIT_L = 8  # TODO
SERVO_ID_READ = 14
SERVO_ANGLE_LIMIT_WRITE = 20
SERVO_ANGLE_LIMIT_READ = 21
#RETURN_LEVEL = 16  # TODO
GOAL_POSITION = 30  # TODO
MOVING_SPEED = 32  # TODO
#BIOLOID_FRAME_LENGTH = 33  # TODO
#PRESENT_LOAD_L = 40  # TODO
PRESENT_TEMP = 26
PRESENT_VOLTAGE = 27
PRESENT_POSITION = 28
#SYNC_WRITE = 131  # TODO
#TORQUE_ENABLE = 24  # TODO
